version: "3"

services:

  node:
    image: node:latest
    container_name: node_upDate
    working_dir: /home/workspace
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./node/workspace:/home/workspace
    networks:
      upDate_network:
        ipv4_address: 172.22.1.2
    depends_on:
      - mongo

  web:
    image: nginx:latest
    container_name: nginx_upDate
    ports:
      - '8080:80'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      upDate_network:
        ipv4_address: 172.22.1.3

  mongo:
    image: mongo:latest
    container_name: mongp_upDate
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command:
      - mongod
    networks:
      upDate_network:
        ipv4_address: 172.22.1.4

networks:
  upDate_network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.1
