version: "3"

services:

  node:
    image: node:latest
    container_name: node_upDate
    working_dir: /home/workspace
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./node/workspace:/home/workspace
    networks:
      upDate_network:
        ipv4_address: 172.22.1.2

  web:
    image: nginx:latest
    container_name: nginx_upDate
    ports:
      - '8080:80'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      upDate_network:
        ipv4_address: 172.22.1.3

networks:
  upDate_network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.1
